#! /usr/local/bin/python3.10
import psutil


FULL = 99

is_plugged = lambda b: b.power_plugged
get_percent = lambda b: round(b.percent)


def main():
    bat = psutil.sensors_battery()
    state = "plugged" if is_plugged(bat) else "unplugged"

    if state == "plugged" and get_percent(bat) > FULL:
        state = "full"

    print(state)


(lambda: main() if __name__ == "__main__" else None)()
