#! /usr/local/bin/python3.10
import psutil


bat = psutil.sensors_battery()
percent = round(bat.percent)
is_plugged = bat.power_plugged


def main():
    print(f"{percent}% ({'plugged' if is_plugged else 'unplugged'})")


(lambda: main() if __name__ == "__main__" else None)()
